spring.application.name=Es6_Videogames
spring.datasource.generate-unique-name=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
server.port=8080
spring.profiles.active=dev
